
import react,  {useEffect, useState, useRef} from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {


const initialTime = 10
const [timerStatus, setTimerStatus] = useState(0); //can be STOP(0) or START(1)
const [timerValue, setTimerValue] = useState(initialTime); //This contains the current time on the counter


function onToggle(){
  timerStatus === 0 ? setTimerStatus(1) :  setTimerStatus(0)
}


 useEffect(() => {
console.log('useeffect')

        const interval = setInterval(() => {
          if(timerStatus === 0) {
             return  
          }
          else{
            setTimerValue(timerValue - 1)
            if(timerValue === 1) {
              setTimerStatus(0)
              setTimerValue(initialTime)
            }

          }
        } , 1000)

        return ()=> {
            clearInterval(interval);
          };

});



 function stopCountDown(){
    console.log('stopped');
 }





  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <header>
        <h1 className={styles.title}>
          Pomodoro Timer
        </h1>
      </header>

      <button onClick={(e) => onToggle(e)}> {timerStatus === 0 ? `start` : `stop`} </button>

      <div>

      Timer 

      <div> {timerValue} </div>

      </div>

      <main className={styles.main}>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
