import React, { useEffect, useState, useRef } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Timer from '../components/Timer.jsx'
import Form from "../components/Form.jsx";



const Pomodoro: NextPage = () => {
  const initialTime = 100; //this is in seconds
  const [timerStatus, setTimerStatus] = useState(false); //can be STOP(false) or START(true)
  const [timerValue, setTimerValue] = useState(initialTime); //This contains the current time on the counter in seconds
  
  useEffect(() => {
    const interval = setInterval(() => {
      if (timerStatus === false) {
        return;
      } else {
        setTimerValue(timerValue - 1);
        if (timerValue === 0) {
          setTimerStatus(false);
          setTimerValue(initialTime);
        }
      }
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Pomorodro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header style={{ padding: "2rem" }}>
        <a href="/">&larr; home</a>
      </header>
      <main className={styles.main}>
        <div>
          <header>
            <h1 className={styles.title}>Pomodoro Timer</h1>
          </header>
        </div>
        <Form setTimerValue={setTimerValue} timerStatus={timerStatus} />
        <Timer
          timerValue={timerValue}
          timerStatus={timerStatus}
          setTimerStatus={setTimerStatus}
        />
      </main>
    </div>
  );
};;

export default Pomodoro;
